"""changed in column name

Revision ID: 039b86e6b06d
Revises: 997f8ad2526d
Create Date: 2024-01-24 16:58:45.577941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039b86e6b06d'
down_revision: Union[str, None] = '997f8ad2526d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_review', sa.Column('book_id', sa.UUID(), nullable=True))
    op.drop_constraint('book_review_blog_id_fkey', 'book_review', type_='foreignkey')
    op.create_foreign_key(None, 'book_review', 'book_information', ['book_id'], ['id'])
    op.drop_column('book_review', 'blog_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_review', sa.Column('blog_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book_review', type_='foreignkey')
    op.create_foreign_key('book_review_blog_id_fkey', 'book_review', 'book_information', ['blog_id'], ['id'])
    op.drop_column('book_review', 'book_id')
    # ### end Alembic commands ###
