"""add review column

Revision ID: 2b98a491d85d
Revises: 401fda0bf071
Create Date: 2024-01-25 10:46:48.064090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b98a491d85d'
down_revision: Union[str, None] = '401fda0bf071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_review', sa.Column('review', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_review', 'review')
    # ### end Alembic commands ###
