"""remove commnet column

Revision ID: 401fda0bf071
Revises: 039b86e6b06d
Create Date: 2024-01-24 17:00:22.779079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401fda0bf071'
down_revision: Union[str, None] = '039b86e6b06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_review', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_review', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
