"""add new table author_detail

Revision ID: 7dd9c6e78efa
Revises: 85b518d79d5b
Create Date: 2024-01-23 16:44:51.466185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dd9c6e78efa'
down_revision: Union[str, None] = '85b518d79d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('email_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modify_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('book_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('blog_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modify_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['book_information.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('book_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('blog_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modify_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['book_information.id'], name='book_reviews_blog_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user_information.id'], name='book_reviews_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='book_reviews_pkey'),
    sa.UniqueConstraint('id', name='book_reviews_id_key')
    )
    op.drop_table('book_review')
    op.drop_table('author_detail')
    # ### end Alembic commands ###
