"""change in column

Revision ID: 7e4d3d4e1b51
Revises: fd472224bc3e
Create Date: 2024-01-23 15:17:51.125627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4d3d4e1b51'
down_revision: Union[str, None] = 'fd472224bc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_information', 'ISBN',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_information', 'ISBN',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###
