"""add column

Revision ID: 85b518d79d5b
Revises: 7e4d3d4e1b51
Create Date: 2024-01-23 15:37:05.398451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85b518d79d5b'
down_revision: Union[str, None] = '7e4d3d4e1b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_information', sa.Column('price', sa.Float(), nullable=True))
    op.alter_column('book_information', 'publication_year',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('book_information', 'ISBN',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_information', 'ISBN',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('book_information', 'publication_year',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('book_information', 'price')
    # ### end Alembic commands ###
