"""change in foreign key value

Revision ID: b5c45a0b647a
Revises: 7dd9c6e78efa
Create Date: 2024-01-23 17:45:55.390265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c45a0b647a'
down_revision: Union[str, None] = '7dd9c6e78efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'author_detail', ['id'])
    op.drop_constraint('book_information_author_id_fkey', 'book_information', type_='foreignkey')
    op.create_foreign_key(None, 'book_information', 'author_detail', ['author_id'], ['id'])
    op.create_unique_constraint(None, 'book_review', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_review', type_='unique')
    op.drop_constraint(None, 'book_information', type_='foreignkey')
    op.create_foreign_key('book_information_author_id_fkey', 'book_information', 'user_information', ['author_id'], ['id'])
    op.drop_constraint(None, 'author_detail', type_='unique')
    # ### end Alembic commands ###
