"""Add new Column in BookInformation table

Revision ID: c7153f32c404
Revises: edcfa7e87f6c
Create Date: 2024-01-23 13:13:27.162491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7153f32c404'
down_revision: Union[str, None] = 'edcfa7e87f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_information', sa.Column('ISBN', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'book_information', ['id'])
    op.create_unique_constraint(None, 'book_reviews', ['id'])
    op.create_unique_constraint(None, 'user_information', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_information', type_='unique')
    op.drop_constraint(None, 'book_reviews', type_='unique')
    op.drop_constraint(None, 'book_information', type_='unique')
    op.drop_column('book_information', 'ISBN')
    # ### end Alembic commands ###
