"""change in column

Revision ID: fd472224bc3e
Revises: aa28c5a4e1c6
Create Date: 2024-01-23 15:01:07.289336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd472224bc3e'
down_revision: Union[str, None] = 'aa28c5a4e1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_information', 'ISBN',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_information', 'ISBN',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
